name = "PGFPlotsX"
uuid = "8314cec4-20b6-5062-9cdb-752b83310925"
version = "1.2.6"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DefaultApplication = "3f0dd361-4fe0-5fc6-8523-80b14ec94d85"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
ArgCheck = "^1, 2.0"
DataStructures = "^0.17"
DefaultApplication = "1"
DocStringExtensions = "^0.8"
MacroTools = "^0.5"
Parameters = "^0.12"
Requires = "0.5, 1.0"
StatsBase = "^0.32, 0.33"
julia = "1"

[extras]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Measurements", "DataFrames", "Colors"]
